# Generated by Django 5.0.3 on 2024-03-26 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("rto", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_vehicle_registration", models.BooleanField(default=False)),
                ("vehicle_no", models.CharField(max_length=50)),
                ("year_of_registration", models.IntegerField()),
                ("chassis_no", models.CharField(max_length=50)),
                ("engine_no", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_image", models.ImageField(upload_to="vehicle_images/")),
                ("back_image", models.ImageField(upload_to="vehicle_images/")),
                ("left_image", models.ImageField(upload_to="vehicle_images/")),
                ("right_image", models.ImageField(upload_to="vehicle_images/")),
                ("rc_image", models.ImageField(upload_to="vehicle_images/")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificate.vehicle",
                    ),
                ),
            ],
        ),
    ]
