# Generated by Django 4.2.3 on 2024-03-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_alter_owner_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleImages',
            new_name='VehicleImage',
        ),
    ]
