# Generated by Django 4.2.3 on 2024-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
