# Generated by Django 5.0.3 on 2024-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0006_vehicle_make"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="transport_office",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="certificate_no",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="class3",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="class4",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="red20mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="red50mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="red80mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_model",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="white20mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="white50mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="white80mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="yellow50mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="yellow80mm",
            field=models.IntegerField(default=0),
        ),
    ]
