# Generated by Django 5.0.3 on 2024-03-27 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0007_owner_transport_office_vehicle_certificate_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="today_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
