# Generated by Django 5.0.3 on 2024-03-27 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0009_owner_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="user",
        ),
    ]
