# Generated by Django 4.2.3 on 2024-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_remove_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='owner',
            name='back_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='certificate_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='chassis_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='class3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='class4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='engine_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='front_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='left_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='new_vehicle_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='rc_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='red20mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='red50mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='red80mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='right_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='vehicle_model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='vehicle_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='white20mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='white50mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='white80mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='year_of_registration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='yellow50mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='yellow80mm',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
