# Generated by Django 5.0.3 on 2024-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "certificate",
            "0013_remove_owner_transport_office_alter_owner_back_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="red20mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="red50mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="red80mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="white20mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="white50mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="white80mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="yellow50mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="yellow80mm",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
