# Generated by Django 5.0.3 on 2024-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0014_alter_owner_red20mm_alter_owner_red50mm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="red20mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="red50mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="red80mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="white20mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="white50mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="white80mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="yellow50mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="yellow80mm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
