# Generated by Django 4.0.10 on 2024-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_alter_owner_red20mm_alter_owner_red50mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='client_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
