# Generated by Django 4.0.10 on 2024-04-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0016_owner_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='client_name',
            new_name='dealer_name',
        ),
    ]
